### ISSUE TITLE
Continuous Deployment is not working

### ISSUE THREAD

**Issue by Irio** [datopian/tech.datopian.com#10]
I recently merged https://github.com/datopian/tech.datopian.com/pull/9, but the changes are not live at tech.datopian.com (15min ago). Possibly, the DNS is still pointing to GitLab.

**Comment by rufuspollock** [comment]
I'm working to fix this.

**Comment by rufuspollock** [comment]
FIXED. Finally in https://github.com/datopian/tech.datopian.com/commit/9b19609eb8da0ccb2f146072219658d780b6d62d
