### ISSUE TITLE
How to create new resource from a file via API with cURL?

### ISSUE THREAD

**Issue by alifk97** [datopian/tech.datopian.com#42]
The following cURL is from: https://tech.datopian.com/ckan/play-around.html#create-organizations-datasets-and-resources
and lets you add a resource to a datset from a url.

curl -X POST http://ckan:5000/api/3/action/resource_create -H "Authorization: 9c04a69d-79f4-4b4b-b4e1-f2ac31ed961c" -d '{
  "package_id": "my-first-dataset",
  "url":  "https://raw.githubusercontent.com/frictionlessdata/test-data/master/files/csv/100kb.csv",
  "description": "This is the best resource ever!" ,
  "name": "brand-new-resource"
}'

Was wondering how you could add a resource from a file.

**Comment by anuveyatsu** [comment]
@alifk97 hi, this is not the CKAN documentation repository. You're probably looking for https://github.com/ckan/ckan
